"use client";

import { useEffect, useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Download, FileSpreadsheet, X } from "lucide-react";
import { loadFinancialBI } from "../lib/finance";

const months=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
const brl=(value:number)=>value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const compact=(value:number)=>new Intl.NumberFormat("pt-BR",{notation:"compact",style:"currency",currency:"BRL"}).format(value);
const relationName=(relation:unknown)=>{const value=Array.isArray(relation)?relation[0]:relation;return value&&typeof value==="object"&&"nome" in value?String((value as {nome?:string}).nome??"Não informado"):"Não informado"};
const excelMoneyFormat='R$ #,##0.00';
type Filters={ano:number;mesInicial:number;mesFinal:number;socioId:string;visualizacao:"Quinzenal"|"Mensal"};

export default function FinancialBI(){
 const [draft,setDraft]=useState<Filters>({ano:2026,mesInicial:6,mesFinal:8,socioId:"",visualizacao:"Quinzenal"}),[filters,setFilters]=useState<Filters>(draft),[data,setData]=useState<any>(null),[error,setError]=useState(""),[detail,setDetail]=useState<any>(null),[selectedCarrier,setSelectedCarrier]=useState("");
 useEffect(()=>{setData(null);setError("");loadFinancialBI({...filters,socioId:filters.socioId||null}).then(setData).catch(e=>setError(e instanceof Error?e.message:"Erro ao carregar BI"))},[filters]);
 const apply=()=>draft.mesInicial>draft.mesFinal?setError("O mês inicial deve ser anterior ao mês final."):setFilters({...draft});
 const quinzenas=useMemo(()=>data?.rows??[],[data]);
 const rows=useMemo(()=>filters.visualizacao==="Quinzenal"?quinzenas:Array.from({length:filters.mesFinal-filters.mesInicial+1},(_,index)=>{
   const mes=filters.mesInicial+index,parts=quinzenas.filter((row:any)=>row.mes===mes),sum=(key:string)=>parts.reduce((total:number,row:any)=>total+Number(row[key]),0),receita=sum("receita"),lucro=sum("lucro");
   return{ano:filters.ano,mes,numero:0,label:`${months[mes-1].slice(0,3)}/${String(filters.ano).slice(2)}`,receita,motoboys:sum("motoboys"),custos:sum("custos"),vales:sum("vales"),extravios:sum("extravios"),lucro,margem:receita?lucro/receita*100:0,hasMovement:parts.some((p:any)=>p.hasMovement),closed:parts.every((p:any)=>p.closed),partners:(data?.partners??[]).map((p:any)=>({...p,received:parts.reduce((a:number,r:any)=>a+(r.partners.find((x:any)=>x.id===p.id)?.received??0),0),paid:parts.reduce((a:number,r:any)=>a+(r.partners.find((x:any)=>x.id===p.id)?.paid??0),0)}))};
 }),[data,filters,quinzenas]);
 const enriched=useMemo(()=>rows.map((row:any,index:number)=>{const previous=[...rows.slice(0,index)].reverse().find((item:any)=>item.hasMovement);const variation=row.hasMovement&&previous&&previous.lucro!==0?(row.lucro-previous.lucro)/Math.abs(previous.lucro)*100:null;return{...row,despesas:row.motoboys+row.custos,variation,receitaVariation:row.hasMovement&&previous&&previous.receita!==0?(row.receita-previous.receita)/Math.abs(previous.receita)*100:null,receitaDifference:row.hasMovement&&previous?row.receita-previous.receita:null,status:periodStatus(row)}}),[rows]);
 if(!data)return <section className="module"><Header/><FiltersBar value={draft} set={setDraft} partners={[]} apply={apply}/><div className={`data-state ${error?"error":""}`}>{error||"Consolidando dados financeiros..."}</div></section>;
 const active=enriched.filter((row:any)=>row.hasMovement),total=(key:string)=>active.reduce((sum:number,row:any)=>sum+Number(row[key]),0),receita=total("receita"),motoboys=total("motoboys"),custos=total("custos"),vales=total("vales"),extravios=total("extravios"),lucro=total("lucro"),margem=receita?lucro/receita*100:0;
 const best=[...active].sort((a:any,b:any)=>b.lucro-a.lucro)[0],highestRevenue=[...active].sort((a:any,b:any)=>b.receita-a.receita)[0],highestExpense=[...active].sort((a:any,b:any)=>b.despesas-a.despesas)[0],last=active.at(-1),growth=last?.variation??null;
 const indicators=[["Melhor quinzena",best?.label??"Sem dados",best?brl(best.lucro):"—"],["Maior receita",highestRevenue?.label??"Sem dados",highestRevenue?brl(highestRevenue.receita):"—"],["Maior despesa",highestExpense?.label??"Sem dados",highestExpense?brl(highestExpense.despesas):"—"],["Margem média","Períodos com movimento",`${(active.reduce((a:number,r:any)=>a+r.margem,0)/(active.length||1)).toFixed(2).replace(".",",")}%`],["Crescimento",last?.label??"Sem dados",growth==null?"Sem comparação disponível":`${growth>=0?"+":""}${growth.toFixed(1).replace(".",",")}%`]];
 const expenses=[{name:"Motoboys",value:motoboys,color:"#c84e4e"},{name:"Custos",value:custos,color:"#e4a52c"},{name:"Vales",value:vales,color:"#3277b8"},{name:"Extravios",value:extravios,color:"#7d5aa6"}];
 const carriers=(data.carriers??[]).map((carrier:any)=>{const periods=quinzenas.filter((row:any)=>row.carriers.some((item:any)=>item.nome===carrier.nome));return{...carrier,count:periods.length,average:periods.length?carrier.receita/periods.length:0}}),carrierTotal=carriers.reduce((a:number,c:any)=>a+c.receita,0),carrierRows=selectedCarrier?quinzenas.map((row:any)=>({label:row.label,receita:row.carriers.find((c:any)=>c.nome===selectedCarrier)?.receita??0})):[];
 const partnerChart=enriched.map((row:any)=>{const caio=row.partners.find((p:any)=>p.nome==="Caio")??{},jose=row.partners.find((p:any)=>p.nome==="José")??{};return{label:row.label,caioRecebeu:caio.received??0,joseRecebeu:jose.received??0,caioPagou:caio.paid??0,josePagou:jose.paid??0}});
 const totals={receita,motoboys,custos,vales,extravios,lucro,margem};
 return <section className="module"><Header actions={<><button className="btn ghost" onClick={()=>exportPdf(filters,totals,indicators,enriched,carriers)}><Download/> Exportar BI em PDF</button><button className="btn primary" onClick={()=>exportExcel(filters,totals,enriched,carriers,quinzenas,data.partners)}><FileSpreadsheet/> Exportar Excel</button></>}/><FiltersBar value={draft} set={setDraft} partners={data.partners} apply={apply}/>{error&&<div className="data-state error">{error}</div>}
 <div className="bi-cards">{[["Receita total",receita,"in"],["Pagamentos aos motoboys",motoboys,"out"],["Custos",custos,"out"],["Vales e extravios",vales+extravios,"warn"],["Lucro líquido",lucro,lucro>=0?"in":"out"]].map(([label,value,color]:any)=><div key={label}><span>{label}</span><b className={color}>{brl(value)}</b></div>)}<div><span>Margem de lucro</span><b className={margem>=0?"in":"out"}>{margem.toFixed(2).replace(".",",")}%</b></div></div>
 <div className="bi-indicators">{indicators.map(([title,label,value])=><div key={title} className={title==="Crescimento"?growth==null?"neutral":growth>=0?"positive":"negative":""}><span>{title}</span><small>{label}</small><b>{value}</b>{title==="Crescimento"&&growth!=null&&<small>Lucro {growth>=0?"cresceu":"caiu"} em relação à quinzena anterior</small>}</div>)}</div>
 <div className="bi-grid"><Chart title="Receita x Despesas x Lucro por Quinzena"><ResponsiveContainer><BarChart data={enriched} onClick={(event:any)=>event?.activePayload?.[0]&&setDetail(event.activePayload[0].payload)}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis tickFormatter={compact}/><Tooltip formatter={(v:any)=>brl(Number(v))}/><Legend/><Bar dataKey="receita" name="Receita" fill="#218a61"/><Bar dataKey="despesas" name="Despesas" fill="#c84e4e"/><Bar dataKey="lucro" name="Lucro líquido" fill="#3277b8"/></BarChart></ResponsiveContainer></Chart>
 <Chart title="Evolução do Lucro por Quinzena"><ResponsiveContainer><LineChart data={enriched} onClick={(event:any)=>event?.activePayload?.[0]&&setDetail(event.activePayload[0].payload)}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis tickFormatter={compact}/><Tooltip content={<CustomTooltip metric="lucro"/>}/><Line connectNulls={false} type="monotone" dataKey={(row:any)=>row.hasMovement?row.lucro:null} name="Lucro" stroke="#218a61" strokeWidth={3}/></LineChart></ResponsiveContainer></Chart>
 <Chart title="Evolução da Receita"><ResponsiveContainer><LineChart data={enriched} onClick={(event:any)=>event?.activePayload?.[0]&&setDetail(event.activePayload[0].payload)}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis tickFormatter={compact}/><Tooltip content={<CustomTooltip metric="receita"/>}/><Line connectNulls={false} type="monotone" dataKey={(row:any)=>row.hasMovement?row.receita:null} name="Receita" stroke="#3277b8" strokeWidth={3}/></LineChart></ResponsiveContainer></Chart>
 <Chart title="Composição das Despesas"><ResponsiveContainer><PieChart><Pie data={expenses} dataKey="value" nameKey="name" innerRadius={55} outerRadius={90}>{expenses.map(item=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip formatter={(v:any)=>brl(Number(v))}/><Legend/></PieChart></ResponsiveContainer></Chart>
 <Chart title="Caio x José"><ResponsiveContainer><BarChart data={partnerChart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis tickFormatter={compact}/><Tooltip formatter={(v:any)=>brl(Number(v))}/><Legend/><Bar dataKey="caioRecebeu" name="Caio recebeu" fill="#218a61"/><Bar dataKey="joseRecebeu" name="José recebeu" fill="#69aa88"/><Bar dataKey="caioPagou" name="Caio pagou" fill="#c84e4e"/><Bar dataKey="josePagou" name="José pagou" fill="#e08a8a"/></BarChart></ResponsiveContainer></Chart>
 <Chart title="Participação na Receita por Transportadora"><div className="carrier-ranking enhanced">{carriers.map((carrier:any)=><button key={carrier.nome} onClick={()=>setSelectedCarrier(carrier.nome)} className={selectedCarrier===carrier.nome?"selected":""}><b>{carrier.nome}</b><span>{brl(carrier.receita)}</span><small>{carrierTotal?(carrier.receita/carrierTotal*100).toFixed(1).replace(".",","):"0,0"}%</small><em>{carrier.count} quinzenas</em><em>Média {brl(carrier.average)}</em></button>)}</div></Chart>
 {selectedCarrier&&<Chart title={`Evolução da Transportadora — ${selectedCarrier}`}><ResponsiveContainer><LineChart data={carrierRows}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis tickFormatter={compact}/><Tooltip formatter={(v:any)=>brl(Number(v))}/><Line type="monotone" dataKey="receita" name="Receita" stroke="#3277b8" strokeWidth={3}/></LineChart></ResponsiveContainer><CarrierStats rows={carrierRows}/></Chart>}</div>
 <section><div className="section-title"><h2>Caio x José</h2><span>Mesma atribuição do Acerto entre Sócios</span></div><div className="partners">{data.partners.map((partner:any)=>{const received=active.reduce((a:number,r:any)=>a+(r.partners.find((p:any)=>p.id===partner.id)?.received??0),0),paid=active.reduce((a:number,r:any)=>a+(r.partners.find((p:any)=>p.id===partner.id)?.paid??0),0);return <Partner key={partner.id} name={partner.nome} received={received} paid={paid} percentage={Number(partner.percentual_participacao)}/>})}</div></section>
 <section><div className="section-title"><h2>Histórico das Quinzenas</h2></div><div className="table-wrap"><table><thead><tr>{["Período","Status","Receita","Motoboys","Custos","Vales/Extravios","Lucro","Margem","Variação"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{[...enriched].reverse().map((row:any)=><tr key={row.label} onClick={()=>row.numero&&setDetail(row)} className="clickable-row"><td>{row.label}</td><td><span className={`bi-status ${statusClass(row.status)}`}>{row.status}</span></td><td>{brl(row.receita)}</td><td>{brl(row.motoboys)}</td><td>{brl(row.custos)}</td><td>{brl(row.vales+row.extravios)}</td><td>{brl(row.lucro)}</td><td>{row.hasMovement?`${row.margem.toFixed(2).replace(".",",")}%`:"—"}</td><td>{row.variation==null?"Sem comparação":`${row.variation>=0?"+":""}${row.variation.toFixed(1).replace(".",",")}%`}</td></tr>)}</tbody></table></div></section>
 {detail&&<DetailModal row={detail} close={()=>setDetail(null)}/>}</section>;
}

function periodStatus(row:any){if(row.closed)return"Fechada";if(row.hasMovement)return"Em aberto";const now=new Date(),periodEnd=new Date(row.ano,row.mes,row.numero===1?15:new Date(row.ano,row.mes,0).getDate(),23,59,59);return periodEnd>=now?"Em aberto":"Sem movimento"}
const statusClass=(status:string)=>status==="Fechada"?"closed":status==="Em aberto"?"open":"empty";
function Header({actions}:{actions?:React.ReactNode}){return <div className="page-head bi-head"><div><span>SUB FLEX FINANCEIRO</span><h1>BI Financeiro</h1></div>{actions&&<div className="bi-actions">{actions}</div>}</div>}
function FiltersBar({value,set,partners,apply}:{value:Filters;set:(v:Filters)=>void;partners:any[];apply:()=>void}){const change=(key:keyof Filters,next:any)=>set({...value,[key]:next});return <div className="bi-filters"><label>Ano<input type="number" value={value.ano} onChange={e=>change("ano",Number(e.target.value))}/></label><label>Mês inicial<select value={value.mesInicial} onChange={e=>change("mesInicial",Number(e.target.value))}>{months.map((m,i)=><option value={i+1} key={m}>{m}</option>)}</select></label><label>Mês final<select value={value.mesFinal} onChange={e=>change("mesFinal",Number(e.target.value))}>{months.map((m,i)=><option value={i+1} key={m}>{m}</option>)}</select></label><label>Sócio<select value={value.socioId} onChange={e=>change("socioId",e.target.value)}><option value="">Todos</option>{partners.map(p=><option value={p.id} key={p.id}>{p.nome}</option>)}</select></label><label>Visualização<select value={value.visualizacao} onChange={e=>change("visualizacao",e.target.value)}><option>Quinzenal</option><option>Mensal</option></select></label><button className="btn primary" onClick={apply}>Aplicar filtros</button></div>}
function Chart({title,children}:{title:string;children:React.ReactNode}){return <div className="bi-chart"><h3>{title}</h3><div>{children}</div></div>}
function CustomTooltip({active,payload,label,metric}:{active?:boolean;payload?:any[];label?:string;metric:"lucro"|"receita"}){if(!active||!payload?.length)return null;const row=payload[0].payload;if(!row.hasMovement)return <div className="bi-tooltip"><b>{label}</b><span>{row.status}</span></div>;const variation=metric==="lucro"?row.variation:row.receitaVariation,difference=metric==="receita"?row.receitaDifference:null;return <div className="bi-tooltip"><b>{label}</b><span>{brl(row[metric])}</span>{difference!==null&&<small>Diferença: {brl(difference)}</small>}<small>{variation==null?"Sem comparação disponível":`${variation>=0?"↑":"↓"} ${Math.abs(variation).toFixed(1).replace(".",",")}% contra o anterior`}</small></div>}
function CarrierStats({rows}:{rows:any[]}){const active=rows.filter(r=>r.receita>0),values=active.map(r=>r.receita),total=values.reduce((a,b)=>a+b,0),max=active.sort((a,b)=>b.receita-a.receita)[0],min=[...active].sort((a,b)=>a.receita-b.receita)[0];return <div className="carrier-stats"><span>Total <b>{brl(total)}</b></span><span>Média <b>{brl(active.length?total/active.length:0)}</b></span><span>Maior <b>{max?`${max.label} • ${brl(max.receita)}`:"—"}</b></span><span>Menor <b>{min?`${min.label} • ${brl(min.receita)}`:"—"}</b></span></div>}
function Partner({name,received,paid,percentage}:{name:string;received:number;paid:number;percentage:number}){return <div className="partner"><div className="partner-name"><span>{name[0]}</span><b>{name}</b></div><dl><div><dt>Recebeu</dt><dd className="in">{brl(received)}</dd></div><div><dt>Pagou</dt><dd className="out">{brl(paid)}</dd></div><div><dt>Saldo</dt><dd>{brl(received-paid)}</dd></div></dl><p>Participação no lucro: {percentage}%</p></div>}
function DetailModal({row,close}:{row:any;close:()=>void}){const details=row.details??{receipts:[],payments:[],costs:[],advances:[]};return <div className="overlay" onMouseDown={close}><div className="modal bi-detail" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><small>DETALHAMENTO DA QUINZENA</small><h2>{row.label}</h2></div><button onClick={close}><X/></button></div><div className="detail-summary">{[["Receita",row.receita],["Motoboys",row.motoboys],["Custos",row.custos],["Vales",row.vales],["Extravios",row.extravios],["Lucro",row.lucro]].map(([l,v]:any)=><span key={l}>{l}<b>{brl(v)}</b></span>)}<span>Margem<b>{row.hasMovement?`${row.margem.toFixed(2).replace(".",",")}%`:"—"}</b></span></div><DetailTable title="Transportadoras" heads={["Nome","Valor recebido","Quem recebeu"]} rows={details.receipts.map((x:any)=>[relationName(x.transportadoras),brl(Number(x.valor)),relationName(x.socios)])}/><DetailTable title="Motoboys" heads={["Nome","Valor pago","Quem pagou","Frequência"]} rows={details.payments.map((x:any)=>[relationName(x.motoboys),brl(Number(x.valor_liquido)),relationName(x.socios),x.tipo_periodo])}/><DetailTable title="Custos" heads={["Descrição","Valor","Quem pagou"]} rows={details.costs.map((x:any)=>[x.descricao,brl(Number(x.valor)),relationName(x.socios)])}/><DetailTable title="Vales/Extravios" heads={["Motoboy","Tipo","Valor"]} rows={details.advances.map((x:any)=>[relationName(x.motoboys),x.tipo,brl(Number(x.valor))])}/></div></div>}
function DetailTable({title,heads,rows}:{title:string;heads:string[];rows:string[][]}){return <section className="detail-section"><h3>{title}</h3><div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>):<tr><td colSpan={heads.length}>Nenhum registro.</td></tr>}</tbody></table></div></section>}

async function exportExcel(filters:Filters,totals:any,rows:any[],carriers:any[],quinzenas:any[],partners:any[]){const XLSX=await import("xlsx");const wb=XLSX.utils.book_new(),moneyColumns=(ws:any,columns:number[])=>{ws["!cols"]=columns.map(()=>({wch:18}));for(const key of Object.keys(ws))if(!key.startsWith("!")){const cell=XLSX.utils.decode_cell(key);if(cell.r>0&&columns.includes(cell.c)&&typeof ws[key].v==="number")ws[key].z=excelMoneyFormat}};const add=(name:string,records:any[],cols:number[]=[])=>{const ws=XLSX.utils.json_to_sheet(records);moneyColumns(ws,cols);XLSX.utils.book_append_sheet(wb,ws,name)};add("Resumo",[{Indicador:"Receita total",Valor:totals.receita},{Indicador:"Pagamentos motoboys",Valor:totals.motoboys},{Indicador:"Custos",Valor:totals.custos},{Indicador:"Vales e extravios",Valor:totals.vales+totals.extravios},{Indicador:"Lucro líquido",Valor:totals.lucro},{Indicador:"Margem (%)",Valor:totals.margem}],[1]);add("Quinzenas",rows.map(r=>({Período:r.label,Status:r.status,Receita:r.receita,Motoboys:r.motoboys,Custos:r.custos,"Vales/Extravios":r.vales+r.extravios,Lucro:r.lucro,"Margem (%)":r.margem,Variação:r.variation??"Sem comparação"})),[2,3,4,5,6]);add("Transportadoras",carriers.map(c=>({Transportadora:c.nome,Receita:c.receita,"Quinzenas com movimento":c.count,"Média por quinzena":c.average})),[1,3]);const all=(key:string)=>quinzenas.flatMap(q=>q.details?.[key]??[]);add("Motoboys",all("payments").map((x:any)=>({Motoboy:relationName(x.motoboys),Valor:Number(x.valor_liquido),Frequência:x.tipo_periodo,"Quem pagou":relationName(x.socios)})),[1]);add("Custos",all("costs").map((x:any)=>({Descrição:x.descricao,Valor:Number(x.valor),"Quem pagou":relationName(x.socios)})),[1]);add("Vales e Extravio",all("advances").map((x:any)=>({Motoboy:relationName(x.motoboys),Tipo:x.tipo,Valor:Number(x.valor)})),[2]);add("Sócios",partners.map(p=>({Sócio:p.nome,"Participação (%)":Number(p.percentual_participacao)})));XLSX.writeFile(wb,`BI-Sub-Flex-${filters.ano}.xlsx`)}
async function exportPdf(filters:Filters,totals:any,indicators:any[],rows:any[],carriers:any[]){const {jsPDF}=await import("jspdf");const pdf=new jsPDF({unit:"mm",format:"a4"}),period=`${months[filters.mesInicial-1]} a ${months[filters.mesFinal-1]} de ${filters.ano}`;let y=18;const title=(text:string)=>{pdf.setFont("helvetica","bold");pdf.setFontSize(14);pdf.setTextColor(28,49,88);pdf.text(text,14,y);y+=8};pdf.setFillColor(28,49,88);pdf.rect(0,0,210,32,"F");pdf.setTextColor(255);pdf.setFontSize(18);pdf.text("Sub Flex Financeiro",14,14);pdf.setFontSize(12);pdf.text("BI Financeiro",14,23);pdf.setTextColor(40);y=42;pdf.text(`Período analisado: ${period} • ${filters.visualizacao}`,14,y);y+=12;title("Resumo financeiro");[["Receita",totals.receita],["Motoboys",totals.motoboys],["Custos",totals.custos],["Vales/Extravios",totals.vales+totals.extravios],["Lucro líquido",totals.lucro]].forEach(([label,value],i)=>{const x=14+(i%2)*92;if(i&&i%2===0)y+=14;pdf.setFontSize(9);pdf.setTextColor(105);pdf.text(String(label),x,y);pdf.setTextColor(35);pdf.setFont("helvetica","bold");pdf.text(brl(Number(value)),x,y+5)});y+=22;title("Indicadores");indicators.forEach(item=>{pdf.setFontSize(9);pdf.setTextColor(55);pdf.text(`${item[0]}: ${item[2]} (${item[1]})`,14,y);y+=6});pdf.addPage();y=18;title("Receita x Despesas x Lucro");drawBars(pdf,rows,14,y,182,58,["receita","despesas","lucro"],["#218a61","#c84e4e","#3277b8"]);y+=70;title("Evolução do lucro e da receita");drawBars(pdf,rows,14,y,182,58,["lucro","receita"],["#218a61","#3277b8"]);pdf.addPage();y=18;title("Composição das despesas");[["Motoboys",totals.motoboys],["Custos",totals.custos],["Vales",totals.vales],["Extravios",totals.extravios]].forEach(([l,v])=>{pdf.setFontSize(10);pdf.text(`${l}: ${brl(Number(v))}`,14,y);y+=7});y+=6;title("Receita por transportadora");carriers.slice(0,15).forEach((c:any,index:number)=>{pdf.setFontSize(9);pdf.text(`${index+1}. ${c.nome} — ${brl(c.receita)} — ${c.count} quinzenas — média ${brl(c.average)}`,14,y);y+=6});pdf.addPage();y=18;title("Histórico das Quinzenas");pdf.setFontSize(7);rows.slice().reverse().forEach((r:any)=>{if(y>280){pdf.addPage();y=18}pdf.text(`${r.label} | ${r.status} | Rec. ${brl(r.receita)} | Mot. ${brl(r.motoboys)} | Cust. ${brl(r.custos)} | Lucro ${brl(r.lucro)} | ${r.hasMovement?r.margem.toFixed(2)+"%":"—"}`,14,y);y+=6});pdf.save(`BI-Sub-Flex-${filters.ano}.pdf`)}
function drawBars(pdf:any,rows:any[],x:number,y:number,w:number,h:number,keys:string[],colors:string[]){const max=Math.max(1,...rows.flatMap(r=>keys.map(k=>Math.abs(Number(r[k]??0))))),group=w/Math.max(rows.length,1);rows.forEach((row,index)=>{keys.forEach((key,k)=>{const value=Math.abs(Number(row[key]??0)),barH=value/max*(h-12),hex=colors[k].replace("#",""),rgb=[parseInt(hex.slice(0,2),16),parseInt(hex.slice(2,4),16),parseInt(hex.slice(4,6),16)];pdf.setFillColor(...rgb);pdf.rect(x+index*group+k*(group/(keys.length+1)),y+h-barH,Math.max(1.5,group/(keys.length+2)),barH,"F")});pdf.setFontSize(5);pdf.setTextColor(90);pdf.text(row.label,x+index*group,y+h+4,{angle:35})});pdf.setDrawColor(190);pdf.line(x,y+h,x+w,y+h)}
