create extension if not exists pgcrypto;
create table if not exists public.socios(id uuid primary key default gen_random_uuid(),nome text not null unique,percentual_participacao numeric(5,2) not null default 50 check(percentual_participacao between 0 and 100),ativo boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.transportadoras(id uuid primary key default gen_random_uuid(),nome text not null unique,tipo_pagamento text not null check(tipo_pagamento in ('semanal','quinzenal')),ativo boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.motoboys(id uuid primary key default gen_random_uuid(),nome text not null unique,tipo_pagamento text not null check(tipo_pagamento in ('semanal','quinzenal')),ativo boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.recebimentos_transportadoras(id uuid primary key default gen_random_uuid(),transportadora_id uuid not null references public.transportadoras(id),tipo_periodo text not null check(tipo_periodo in ('semanal','quinzenal')),numero_periodo smallint not null,mes smallint not null check(mes between 1 and 12),ano smallint not null,data_referencia date not null,valor numeric(14,2) not null default 0,status text not null default 'pendente' check(status in ('pendente','recebido','cancelado')),recebido_por_socio_id uuid references public.socios(id),observacoes text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.pagamentos_motoboys(id uuid primary key default gen_random_uuid(),motoboy_id uuid not null references public.motoboys(id),tipo_periodo text not null check(tipo_periodo in ('semanal','quinzenal')),numero_periodo smallint not null,mes smallint not null check(mes between 1 and 12),ano smallint not null,valor_bruto numeric(14,2) not null default 0,valor_vales numeric(14,2) not null default 0,valor_extravios numeric(14,2) not null default 0,outros_descontos numeric(14,2) not null default 0,acrescimos numeric(14,2) not null default 0,valor_liquido numeric(14,2) generated always as (round(valor_bruto-valor_vales-valor_extravios-outros_descontos+acrescimos,2)) stored,status text not null default 'pendente' check(status in ('pendente','pago','cancelado')),pago_por_socio_id uuid references public.socios(id),data_pagamento date,observacoes text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.custos(id uuid primary key default gen_random_uuid(),tipo text not null check(tipo in ('fixo','variavel')),categoria text not null,descricao text not null,valor numeric(14,2) not null,data date not null,mes smallint not null,ano smallint not null,status text not null default 'pendente',pago_por_socio_id uuid references public.socios(id),observacoes text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.fechamentos(id uuid primary key default gen_random_uuid(),tipo_periodo text not null,numero_periodo smallint not null,mes smallint not null,ano smallint not null,total_recebido numeric(14,2) not null default 0,total_pago_motoboys numeric(14,2) not null default 0,total_custos numeric(14,2) not null default 0,total_vales numeric(14,2) not null default 0,total_extravios numeric(14,2) not null default 0,lucro_liquido numeric(14,2) not null default 0,percentual_caio numeric(5,2) not null,percentual_jose numeric(5,2) not null,lucro_caio numeric(14,2) not null default 0,lucro_jose numeric(14,2) not null default 0,saldo_caio numeric(14,2) not null default 0,saldo_jose numeric(14,2) not null default 0,valor_repasse numeric(14,2) not null default 0,socio_pagador_id uuid references public.socios(id),socio_recebedor_id uuid references public.socios(id),status text not null default 'aberto',fechado_por uuid references auth.users(id),fechado_em timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.vales_extravios(id uuid primary key default gen_random_uuid(),tipo text not null check(tipo in ('vale','extravio')),motoboy_id uuid not null references public.motoboys(id),valor numeric(14,2) not null,data date not null,periodo_desconto smallint not null,mes_desconto smallint not null,ano_desconto smallint not null,realizado_por_socio_id uuid references public.socios(id),status text not null default 'pendente',fechamento_id uuid references public.fechamentos(id),observacoes text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.repasses_socios(id uuid primary key default gen_random_uuid(),fechamento_id uuid references public.fechamentos(id),socio_pagador_id uuid not null references public.socios(id),socio_recebedor_id uuid not null references public.socios(id),valor_previsto numeric(14,2) not null,valor_pago numeric(14,2) not null,data date not null,status text not null default 'pendente',observacoes text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.configuracoes(id uuid primary key default gen_random_uuid(),chave text not null unique,valor text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.historico_alteracoes(id bigint generated always as identity primary key,tabela text not null,registro_id uuid not null,acao text not null,dados_anteriores jsonb,dados_novos jsonb,usuario_id uuid references auth.users(id),created_at timestamptz not null default now());

