create extension if not exists "pgcrypto";
create type public.user_role as enum ('administrador','socio');
create type public.record_status as enum ('ativo','inativo','cancelado','excluido');
create type public.payment_frequency as enum ('semanal','quinzenal');

create table public.usuarios (id uuid primary key references auth.users(id), nome text not null, email text not null unique, perfil user_role not null default 'socio', status record_status not null default 'ativo', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.socios (id uuid primary key default gen_random_uuid(), usuario_id uuid references public.usuarios(id), nome text not null, percentual numeric(5,2) not null check(percentual between 0 and 100), status record_status not null default 'ativo', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references public.usuarios(id));
create table public.transportadoras (id uuid primary key default gen_random_uuid(), nome text not null, frequencia_padrao payment_frequency not null, observacoes text, status record_status not null default 'ativo', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references public.usuarios(id));
create table public.motoboys (id uuid primary key default gen_random_uuid(), nome text not null, telefone text, frequencia payment_frequency not null, data_entrada date not null default current_date, observacoes text, status record_status not null default 'ativo', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references public.usuarios(id));
create table public.historico_frequencia_motoboy (id uuid primary key default gen_random_uuid(), motoboy_id uuid not null references public.motoboys(id), frequencia payment_frequency not null, inicio date not null, fim date, created_at timestamptz not null default now(), created_by uuid references public.usuarios(id));
create table public.faturas_transportadoras (id uuid primary key default gen_random_uuid(), transportadora_id uuid not null references public.transportadoras(id), frequencia payment_frequency not null, periodo_inicio date not null, periodo_fim date not null, data_recebimento date, valor_fatura numeric(14,2) not null check(valor_fatura>=0), valor_recebido numeric(14,2) not null default 0 check(valor_recebido>=0), recebido_por uuid references public.socios(id), status text not null check(status in ('a_receber','recebido','parcial','cancelado','excluido')), observacoes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references public.usuarios(id), constraint recebimento_valido check(valor_recebido<=valor_fatura));
create table public.fechamentos (id uuid primary key default gen_random_uuid(), frequencia payment_frequency not null, periodo_inicio date not null, periodo_fim date not null, status text not null default 'aberto' check(status in ('aberto','finalizado','reaberto','cancelado')), finalizado_at timestamptz, reabertura_motivo text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references public.usuarios(id));
create table public.vales_extravios (id uuid primary key default gen_random_uuid(), tipo text not null check(tipo in ('vale','extravio')), motoboy_id uuid not null references public.motoboys(id), data date not null, valor numeric(14,2) not null check(valor>0), motivo text not null, realizado_por uuid references public.socios(id), fechamento_id uuid references public.fechamentos(id), status text not null default 'pendente' check(status in ('pendente','descontado','cancelado')), observacoes text, comprovante_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references public.usuarios(id), constraint desconto_unico unique(id,fechamento_id));
create table public.pagamentos_motoboys (id uuid primary key default gen_random_uuid(), fechamento_id uuid references public.fechamentos(id), motoboy_id uuid not null references public.motoboys(id), periodo_inicio date not null, periodo_fim date not null, valor_bruto numeric(14,2) not null, vales numeric(14,2) not null default 0, extravios numeric(14,2) not null default 0, outros_descontos numeric(14,2) not null default 0, acrescimos numeric(14,2) not null default 0, valor_liquido numeric(14,2) generated always as (valor_bruto-vales-extravios-outros_descontos+acrescimos) stored, pago_por uuid references public.socios(id), data_pagamento date, status text not null default 'pendente' check(status in ('pendente','pago','parcial','cancelado')), observacoes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references public.usuarios(id));
create table public.custos (id uuid primary key default gen_random_uuid(), tipo text not null check(tipo in ('fixo','variavel')), descricao text not null, categoria text not null, competencia date, vencimento date, data_pagamento date, valor numeric(14,2) not null check(valor>0), pago_por uuid references public.socios(id), recorrente boolean not null default false, status text not null default 'pendente', observacoes text, comprovante_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references public.usuarios(id));
create table public.repasses_socios (id uuid primary key default gen_random_uuid(), socio_origem uuid not null references public.socios(id), socio_destino uuid not null references public.socios(id), valor numeric(14,2) not null check(valor>0), data date not null, status text not null default 'pendente', observacoes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references public.usuarios(id));
create table public.configuracoes (id uuid primary key default gen_random_uuid(), chave text not null unique, valor text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references public.usuarios(id));
create table public.historico_alteracoes (id bigint generated always as identity primary key, tabela text not null, registro_id uuid not null, acao text not null, dados_anteriores jsonb, dados_novos jsonb, motivo text, created_at timestamptz not null default now(), created_by uuid references public.usuarios(id));

create index on public.faturas_transportadoras(transportadora_id,periodo_inicio);
create index on public.pagamentos_motoboys(motoboy_id,periodo_inicio);
create index on public.vales_extravios(motoboy_id,status);
create index on public.custos(data_pagamento,tipo);

alter table public.usuarios enable row level security; alter table public.socios enable row level security; alter table public.transportadoras enable row level security; alter table public.motoboys enable row level security; alter table public.historico_frequencia_motoboy enable row level security; alter table public.faturas_transportadoras enable row level security; alter table public.fechamentos enable row level security; alter table public.vales_extravios enable row level security; alter table public.pagamentos_motoboys enable row level security; alter table public.custos enable row level security; alter table public.repasses_socios enable row level security; alter table public.configuracoes enable row level security; alter table public.historico_alteracoes enable row level security;

create or replace function public.usuario_ativo() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from usuarios where id=auth.uid() and status='ativo') $$;
create or replace function public.eh_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from usuarios where id=auth.uid() and perfil='administrador' and status='ativo') $$;
do $$ declare t text; begin foreach t in array array['socios','transportadoras','motoboys','historico_frequencia_motoboy','faturas_transportadoras','fechamentos','vales_extravios','pagamentos_motoboys','custos','repasses_socios','configuracoes','historico_alteracoes'] loop execute format('create policy "leitura autenticada" on public.%I for select to authenticated using (public.usuario_ativo())',t); execute format('create policy "escrita autenticada" on public.%I for insert to authenticated with check (public.usuario_ativo())',t); execute format('create policy "atualizacao autenticada" on public.%I for update to authenticated using (public.usuario_ativo()) with check (public.usuario_ativo())',t); end loop; end $$;
create policy "perfil proprio" on public.usuarios for select to authenticated using(id=auth.uid() or public.eh_admin());
create policy "admin gerencia usuarios" on public.usuarios for all to authenticated using(public.eh_admin()) with check(public.eh_admin());

insert into public.motoboys(nome,frequencia) values ('Angelo Kaique','quinzenal'),('Thiago Alves','quinzenal'),('Lucas Kaique','quinzenal'),('Antonio','semanal'),('Augusto','semanal'),('Jefferson','semanal'),('Vinicius','semanal'),('Lucas','semanal'),('Matheus','semanal'),('Ronaldo','semanal'),('Gabriel','semanal'),('Joadson','semanal'),('Eduardo','semanal');

